### ISSUE TITLE
Release to crates.io

### ISSUE THREAD

**Issue by Polochon-street** [gyng/rcue#9]
Hi!

First off, thank you very much for your work on `rcue` - it's the only "pure-rust" CUE crate, and the API looks indeed very rust-y :)

I was wondering whether you could release it to `crates.io`? I would really like to use it in [my crate](https://github.com/Polochon-street/bliss-rs), but that would mean I couldn't release new versions of it through crates.io (since the dependencies need to all be fixed).

`cargo publish` should do the trick :grin: 
Cheers,
Paul

**Comment by gyng** [comment]
Thanks for choosing rcue 😛! Never thought this toy project would be used but I just released it to https://crates.io/crates/rcue.

**Comment by Polochon-street** [comment]
thanks a lot! :smile:
